-- 급여가 15000 이상인 직원 조회
SELECT *
FROM EMPLOYEES
WHERE SALARY >= 15000;

-- 입사년도가 2005년인 직원 조회
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE >= '2005-01-01' AND HIRE_DATE <= '2005-12-31';

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '2005-01-01' AND '2005-12-31';

-- 부서이름이 IT인 직원 조회
SELECT *
FROM EMPLOYEES;

SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'IT';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- 직원을 First_Name을 기준으로 오름차순 정렬해서 조회
SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME ASC;

SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME DESC;

-- SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, SALARY
SELECT 
    EMPLOYEE_ID
    , FIRST_NAME || ' '  || LAST_NAME AS NAME -- 수직바 2개 (||)를 사용해서 문자열 결합
    , EMAIL
    , PHONE_NUMBER
    , HIRE_DATE
    , SALARY
FROM EMPLOYEES
ORDER BY FIRST_NAME ASC;

-- 전화번호가 590으로 시작하는 직원 조회
DESC EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '590%';

-- 관리자별로(Manager_ID) 관리 대상 직원의 수를 조회
SELECT 
    MANAGER_ID
    , COUNT(*) "직원수"
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL -- NULL 비교는 비교 연산자를 사용할 수 없습니다. = OR != OR <>
GROUP BY MANAGER_ID;

-- 업무(JOB_ID)별로 직원 수, 급여 평균, 최대 급여, 최소 급여를 조회
SELECT 
    JOB_ID
    , COUNT(*) "직원수"
    , AVG(SALARY) "급여평균"
    , MIN(SALARY) "최저급여"
    , MAX(SALARY) "최고급여"
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY AVG(SALARY) DESC;

SELECT *
FROM JOBS;






