-- 주문 테이블과 고객 테이블을 결합해서 조회하세요

SELECT *
FROM CUSTOMER, ORDERS;

-- 고객이름, 주소, 전화번호를 고객의 주문에 관한 데이터와 함께 조회하세요
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

SELECT CUSTOMER.CUSTID, NAME, ORDERID, BOOKID, SALEPRICE, ORDERDATE
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID;

SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C, ORDERS O -- 테이블 이름 ALIAS
WHERE C.CUSTID = O.CUSTID;

SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID;

-- 고객이름, 주소, 전화번호를 고객의 주문에 관한 데이터와 함께 고객번호 순으로 정렬하여 조회하세요
SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C, ORDERS O -- 테이블 이름 ALIAS
WHERE C.CUSTID = O.CUSTID
ORDER BY C.CUSTID;

SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
ORDER BY C.CUSTID;

-- 고객의 이름과 고객이 주문한 도서의 판매가격을 검색하시오
SELECT C.NAME "고객명", O.SALEPRICE "판매가격"
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID;

SELECT C.NAME "고객명", O.SALEPRICE "판매가격"
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID;

-- 고객별로 주문한 모든 도서의 총 판매액을 구하고, 고객의 이름으로 정렬해서 조회하세요.
SELECT C.NAME "고객명", SUM(O.SALEPRICE) "총판매액"
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID
GROUP BY C.NAME
ORDER BY C.NAME;

SELECT C.NAME "고객명", SUM(O.SALEPRICE) "총판매액"
FROM ORDERS O
INNER JOIN CUSTOMER C
ON O.CUSTID = C.CUSTID
GROUP BY C.NAME
ORDER BY C.NAME;