-- 주문 테이블과 고객 테이블을 결합해서 조회하세요

SELECT *
FROM CUSTOMER, ORDERS;

-- 고객이름, 주소, 전화번호를 고객의 주문에 관한 데이터와 함께 조회하세요
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

SELECT CUSTOMER.CUSTID, NAME, ORDERID, BOOKID, SALEPRICE, ORDERDATE
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTID = ORDERS.CUSTID;

SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C, ORDERS O -- 테이블 이름 ALIAS
WHERE C.CUSTID = O.CUSTID;

SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID;

-- 고객이름, 주소, 전화번호를 고객의 주문에 관한 데이터와 함께 고객번호 순으로 정렬하여 조회하세요
SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C, ORDERS O -- 테이블 이름 ALIAS
WHERE C.CUSTID = O.CUSTID
ORDER BY C.CUSTID;

SELECT C.CUSTID, C.NAME, O.ORDERID, O.BOOKID, O.SALEPRICE, O.ORDERDATE
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
ORDER BY C.CUSTID;

-- 고객의 이름과 고객이 주문한 도서의 판매가격을 검색하시오
SELECT C.NAME "고객명", O.SALEPRICE "판매가격"
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID;

SELECT C.NAME "고객명", O.SALEPRICE "판매가격"
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID;

-- 고객별로 주문한 모든 도서의 총 판매액을 구하고, 고객의 이름으로 정렬해서 조회하세요.
SELECT C.NAME "고객명", SUM(O.SALEPRICE) "총판매액"
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID
GROUP BY C.NAME
ORDER BY C.NAME;

SELECT C.NAME "고객명", SUM(O.SALEPRICE) "총판매액"
FROM ORDERS O
INNER JOIN CUSTOMER C
ON O.CUSTID = C.CUSTID
GROUP BY C.NAME
ORDER BY C.NAME;

-- Customer 테이블의 고객의 이름과 고객이 주문한 Book 테이블의 도서의 이름을 구하시오

SELECT * FROM CUSTOMER C; -- CUSTOMER 테이블은 BOOK 테이블과 직접적인 관계가 없습니다.
SELECT * FROM BOOK B; -- BOOK 테이블은 CUSTOMER 테이블과 직접적인 관계가 없습니다.

SELECT 
    C.NAME "고객명" 
    , B.BOOKNAME "도서명"
    , O.SALEPRICE "주문금액"
    , O.ORDERDATE "주문일자"
FROM CUSTOMER C, ORDERS O, BOOK B
WHERE C.CUSTID = O.CUSTID AND O.BOOKID = B.BOOKID;

SELECT 
    C.NAME "고객명" 
    , B.BOOKNAME "도서명"
    , O.SALEPRICE "주문금액"
    , O.ORDERDATE "주문일자"
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B
ON O.BOOKID = B.BOOKID;

-- 가격이 20,000원인 도서를 주문한 고객의 이름과 도서의 이름, 판매가격, 주문일자을 구하시오.
-- (JOIN 조건과 일반조건 결합)
SELECT 
    C.NAME "고객명" 
    , B.BOOKNAME "도서명"
    , O.SALEPRICE "주문금액"
    , O.ORDERDATE "주문일자"
FROM CUSTOMER C, ORDERS O, BOOK B
WHERE C.CUSTID = O.CUSTID AND O.BOOKID = B.BOOKID AND O.SALEPRICE = 20000;

SELECT 
    C.NAME "고객명" 
    , B.BOOKNAME "도서명"
    , O.SALEPRICE "주문금액"
    , O.ORDERDATE "주문일자"
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
INNER JOIN BOOK B
ON O.BOOKID = B.BOOKID
WHERE O.SALEPRICE = 20000;

-- 도서를 구매하지 않은 고객을 포함하여 고객의 이름과 고객이 주문한 도서의 판매가격을 구하시오
SELECT C.NAME "고객명", O.SALEPRICE "판매가격"
FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUSTID = O.CUSTID;

SELECT C.NAME "고객명", NVL(O.SALEPRICE, 0) "판매가격"
FROM CUSTOMER C
LEFT OUTER JOIN ORDERS O
ON C.CUSTID = O.CUSTID
ORDER BY C.NAME;

SELECT C.NAME "고객명", NVL(O.SALEPRICE, 0) "판매가격"
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID(+) -- ORACLE OUTER JOIN
ORDER BY C.NAME;

























