-- 가장 비싼 도서의 이름을 보이시오

SELECT * FROM BOOK ORDER BY PRICE DESC;

SELECT MAX(PRICE) FROM BOOK;
SELECT * FROM BOOK WHERE PRICE = 35000;

SELECT * FROM BOOK WHERE PRICE = ( SELECT MAX(PRICE) FROM BOOK );

-- 도서를 구매한 적이 있는 고객의 이름을 검색하시오
SELECT DISTINCT C.NAME
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID;

SELECT DISTINCT CUSTID
FROM ORDERS;

SELECT *
FROM CUSTOMER C
WHERE C.CUSTID IN ( 1, 2, 3, 4 );-- 구매한 적이 있는

SELECT *
FROM CUSTOMER C
WHERE C.CUSTID IN ( SELECT DISTINCT CUSTID
                    FROM ORDERS );-- 구매한 적이 있는
                    
-- 대한미디어에서 출판한 도서를 구매한 고객의 이름을 보이시오.

SELECT * FROM BOOK WHERE PUBLISHER = '대한미디어'; -- ( BOOKID : 3, 4 )

SELECT * FROM ORDERS WHERE BOOKID IN ( 3, 4 ); -- ( CUSTID : 1 )

SELECT * FROM CUSTOMER WHERE CUSTID IN ( 1 );

SELECT * 
FROM CUSTOMER 
WHERE CUSTID IN ( SELECT CUSTID 
                  FROM ORDERS 
                  WHERE BOOKID IN ( SELECT BOOKID
                                    FROM BOOK 
                                    WHERE PUBLISHER = '대한미디어' ) );
                                    
SELECT C.*
FROM CUSTOMER C, ORDERS O, BOOK B
WHERE C.CUSTID = O.CUSTID
      AND
      O.BOOKID = B.BOOKID
      AND 
      PUBLISHER = '대한미디어';
      
SELECT C.*
FROM BOOK B
INNER JOIN ORDERS O
ON B.BOOKID = O.BOOKID
INNER JOIN CUSTOMER C
ON O.CUSTID = C.CUSTID
WHERE B.PUBLISHER = '대한미디어';

-- 출판사별로 출판사의 평균 도서 가격보다 비싼 도서를 구하시오

SELECT PUBLISHER, AVG(PRICE)
FROM BOOK
GROUP BY PUBLISHER; -- 이상미디어 16500, ...

SELECT *
FROM BOOK
WHERE PRICE > 16500 AND PUBLISHER = '이상미디어'; -- 각 출판사의 평균가격과 출판사 이름을 적용해서 실행

SELECT B1.*
FROM BOOK B1
WHERE B1.PRICE >= ( SELECT AVG(B2.PRICE)
                    FROM BOOK B2
                    WHERE B2.PUBLISHER = B1.PUBLISHER );
                    
-- 주문이 있는 고객의 이름과 주소를 보이시오
SELECT DISTINCT C.NAME, C.ADDRESS
FROM CUSTOMER C, ORDERS O
WHERE C.CUSTID = O.CUSTID;

SELECT C.CUSTID, C.NAME, C.ADDRESS
FROM CUSTOMER C
WHERE EXISTS ( SELECT *
               FROM ORDERS O
               WHERE O.CUSTID = C.CUSTID );

SELECT C.CUSTID, C.NAME, C.ADDRESS
FROM CUSTOMER C
WHERE C.CUSTID IN ( SELECT O.CUSTID
                   FROM ORDERS O
                   WHERE O.CUSTID = C.CUSTID );














                    