-- Book 테이블에 새로운 도서 ‘스포츠 의학’을 삽입하시오. 
-- 스포츠 의학은 한솔의학서적에서 출간했으며 가격은 90,000원이다.

ALTER TABLE BOOK MODIFY BOOKID NUMBER;
DESC BOOK;

INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES (98, '스포츠의학-OCH', '한솔의학서적', 90000);
COMMIT; -- 임시 저장된 작업을 확정 ( ROLLBACK은 임시 저장된 작업 취소 )

SELECT * FROM BOOK;

-- 데이터 삭제
DELETE FROM BOOK 
WHERE BOOKID = 98;
COMMIT;
SELECT * FROM BOOK;

--Book 테이블에 새로운 도서 ‘스포츠 의학’을 삽입하시오. 스포츠 의학은
--한솔의학서적에서 출간했으며 가격은 미정이다.

DESC BOOK;

INSERT INTO BOOK (BOOKID, BOOKNAME, PUBLISHER)
VALUES (98, '스포츠 의학-OCH', '한솔의학서적');
COMMIT;
SELECT * FROM BOOK;

DELETE FROM BOOK WHERE BOOKID = 98;
COMMIT;
SELECT * FROM BOOK;

-- 수입도서 목록(Imported_book)을 Book 테이블에 모두 삽입하시오 
CREATE TABLE NEWBOOK_OCH
(
    BOOKID NUMBER
    , BOOKNAME VARCHAR2 (20)
    , PUBLISHER VARCHAR2 (20)
    , PRICE NUMBER
);
SELECT * FROM NEWBOOK_OCH;

INSERT INTO NEWBOOK_OCH (BOOKID, BOOKNAME, PUBLISHER, PRICE)
SELECT BOOKID, BOOKNAME, PUBLISHER, PRICE
FROM IMPORTED_BOOK;

COMMIT;

SELECT * FROM NEWBOOK_OCH;

-- Customer 테이블에서 고객번호가 5인 고객의 주소를 ‘대한민국 부산’으로 변경하시오
DESC CUSTOMER;

INSERT INTO CUSTOMER (CUSTID, NAME, ADDRESS, PHONE)
VALUES (98, '장동건', '대한민국 서울', '010-9807-4599');
COMMIT;

SELECT * FROM CUSTOMER;

UPDATE CUSTOMER
SET ADDRESS = '대한민국 울산', PHONE = '010-7680-3498'
WHERE CUSTID = 98;
COMMIT;

SELECT * FROM CUSTOMER;

-- Customer 테이블에서 박세리 고객의 주소를 김연아 고객의 주소로 변경하시오
UPDATE CUSTOMER
SET ADDRESS = ( SELECT ADDRESS 
                FROM CUSTOMER
                WHERE NAME = '김연아' )
WHERE CUSTID = 98;
COMMIT;

SELECT * FROM CUSTOMER;

--

SELECT * FROM NEWBOOK_OCH;
DELETE FROM NEWBOOK_OCH;
SELECT * FROM NEWBOOK_OCH;
ROLLBACK; -- 마지막 COMMIT OR ROLLBACK 이후에 실행된 임시 작업 취소
SELECT * FROM NEWBOOK_OCH;

-- Customer 테이블에서 고객번호가 4인 고객을 삭제하시오
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

DELETE FROM CUSTOMER 
WHERE CUSTID = 5;


